project_name: 'dh-debug'

#before:
#  hooks:
#  - go generate ./...

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ingshtrom/dh-debug/misc.Version={{ .Version}} -X github.com/ingshtrom/dh-debug/misc.Date={{ .Date}}

archives:
  - replacements:
      darwin: 'Darwin'
      linux: 'Linux'
      windows: 'Windows'
      386: 'i386'
      amd64: 'x86_64'
